sudo: required

branches:
  only:
    - master

cache:
  directories:
    - $PWD/packages

services:
  - docker

before_install:
    - openssl aes-256-cbc -K $encrypted_42099b4af021_key -iv $encrypted_42099b4af021_iv -in myPreciousKey.enc -out myPreciousKey -d
    - eval "$(ssh-agent -s)"
    - chmod 600 myPreciousKey
    - ssh-add myPreciousKey

    - docker build -t webapp:test -f dockerfile/test .
script:
    #- docker run -it --rm -v $HOME/cache:/root/.nuget/packages webapp:test
    #- docker run -it --rm -v $PWD/publish:/root/publish -v $PWD/packages:/root/.nuget/packages webapp:test
    #- docker build -t webapp:release -f ./dockerfile/release .

    - chmod ugo-x scripts/travisCI.sh
    - sh ./scripts/travisCI.sh
